table DimCustomer
	lineageTag: 54a688ca-5da2-4fe0-9965-09914965888f

	column CustomerId
		dataType: int64
		formatString: 0
		lineageTag: a3a01fb6-3ac7-4828-a21b-1cd41a79f6ea
		summarizeBy: none
		sourceColumn: CustomerId

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: b8f79868-e8ba-4128-9e05-e810588e09f2
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: c2782f3b-dee2-4167-b2f6-51798b465125
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: f0d4e76f-7a07-48db-a3a3-4a4cba6b2410
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 2ccd4d20-aaf7-42b8-aeaf-96d474c26f2a
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 13317c2d-eeaa-4741-9467-c8b8c694d40a
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 9a9d2c33-792b-4b87-9f1e-c536afd1b45e
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 1606f60e-d313-4646-a3e6-c764c690a798
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column PostalCode
		dataType: string
		lineageTag: f01e4bc8-144c-41eb-8741-863b70179ce0
		summarizeBy: none
		sourceColumn: PostalCode

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: e1152e84-7e10-4bf8-b8b1-e7a23623b3b0
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Fax
		dataType: string
		lineageTag: 181b6d72-0ded-4c58-abe2-c59ed02d1ef0
		summarizeBy: none
		sourceColumn: Fax

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 4d4197d2-6a39-4051-890f-2cfe33029c2c
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column SupportRepId
		dataType: int64
		formatString: 0
		lineageTag: 1c5f2eb1-c94a-463a-be0b-47c30137294b
		summarizeBy: none
		sourceColumn: SupportRepId

		annotation SummarizationSetBy = Automatic

	column Employee_LastName
		dataType: string
		lineageTag: ce436587-a6ce-4f4c-89ac-a83104dca878
		summarizeBy: none
		sourceColumn: Employee_LastName

		annotation SummarizationSetBy = Automatic

	column Employee_FirstName
		dataType: string
		lineageTag: bc5a0fe6-a0f0-4caf-89fd-17f50880e373
		summarizeBy: none
		sourceColumn: Employee_FirstName

		annotation SummarizationSetBy = Automatic

	column Employee_Email
		dataType: string
		lineageTag: caea2940-7e0f-4649-bae2-4552f4a59bcc
		summarizeBy: none
		sourceColumn: Employee_Email

		annotation SummarizationSetBy = Automatic

	column 'Individual or Business' = IF(ISBLANK(DimCustomer[Company]),"Individual","Business")
		lineageTag: 12afa183-b5c2-4f4c-8a1c-b703a4d76e06
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Name' =
			
			VAR _name = DimCustomer[FirstName] & " " & DimCustomer[LastName]
			VAR _count =
			    COUNTROWS (
			        FILTER (
			            ALL ( DimCustomer ),
			            DimCustomer[FirstName] & " " & DimCustomer[LastName] = _name
			        )
			    )
			RETURN
			    IF ( _count > 1, _name & " (" & DimCustomer[CustomerId] & ")", _name )
		lineageTag: a0a8fd02-8804-454c-8f77-a9e25e32f8bf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		source =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "customer"]}[Data],
				    #"Expanded chinook.employee" = Table.ExpandRecordColumn(#"Navigation 1", "chinook.employee", {"LastName", "FirstName", "Email"}, {"chinook.employee.LastName", "chinook.employee.FirstName", "chinook.employee.Email"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded chinook.employee",{{"chinook.employee.LastName", "Employee_LastName"}, {"chinook.employee.FirstName", "Employee_FirstName"}, {"chinook.employee.Email", "Employee_Email"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"chinook.invoice"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

