createOrReplace

	model Model
		culture: en-US
		defaultPowerBIDataSourceVersion: powerBI_V3
		discourageImplicitMeasures
		sourceQueryCulture: en-IN
		valueFilterBehavior: independent
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table BridgePlaylisttrack
			lineageTag: 852e8991-10e9-4adc-a739-c803f2eec97b

			column PlaylistId
				dataType: int64
				formatString: 0
				lineageTag: 75f288df-1104-4262-ad5b-1784c6df7172
				summarizeBy: none
				sourceColumn: PlaylistId

				annotation SummarizationSetBy = Automatic

			column TrackId
				dataType: int64
				formatString: 0
				lineageTag: 82e28b08-fe94-4c82-aa9e-353990e97f0e
				summarizeBy: none
				sourceColumn: TrackId

				annotation SummarizationSetBy = Automatic

			partition BridgePlaylisttrack = m
				mode: import
				source =
						let
						  Source = MySQL.Database("localhost:3306", "chinook"),
						  #"Navigation 1" = Source{[Schema = "chinook", Item = "playlisttrack"]}[Data],
						    #"Removed Columns" = Table.RemoveColumns(#"Navigation 1",{"chinook.track", "chinook.playlist"})
						in
						    #"Removed Columns"

			changedProperty = Name

			annotation PBI_ResultType = Table

			annotation PBI_NavigationStepName = Navigation

		table FactSales
			lineageTag: a373dbed-3ba1-4880-bc2b-fa2263f031fe

			column InvoiceLineId
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: e7469481-4082-4f95-abf1-09035e861d7a
				summarizeBy: none
				sourceColumn: InvoiceLineId

				changedProperty = IsHidden

				annotation SummarizationSetBy = User

			column InvoiceId
				dataType: int64
				formatString: 0
				lineageTag: 1b86e457-ff14-4f8b-a478-065ec97b900b
				summarizeBy: none
				sourceColumn: InvoiceId

				changedProperty = IsHidden

				annotation SummarizationSetBy = User

			column TrackId
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: 765cb33b-5d54-4364-865f-a75a34ee88ad
				summarizeBy: none
				sourceColumn: TrackId

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column UnitPrice
				dataType: double
				lineageTag: 59bc9ec8-1bd8-4e77-bb57-803cf74c01fc
				summarizeBy: sum
				sourceColumn: UnitPrice

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column Quantity
				dataType: int64
				formatString: 0
				lineageTag: d474b074-e82d-4e07-8119-42fd183055c4
				summarizeBy: sum
				sourceColumn: Quantity

				annotation SummarizationSetBy = Automatic

			column CustomerId
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: 21f6a973-a7a2-49c6-82c0-4ca9ec4bcb90
				summarizeBy: none
				sourceColumn: CustomerId

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column InvoiceDate
				dataType: dateTime
				isHidden
				formatString: Long Date
				lineageTag: 1772547f-f89b-4754-a847-583a5c4341e0
				summarizeBy: none
				sourceColumn: InvoiceDate

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			partition FactSales = m
				mode: import
				source =
						let
						  Source = MySQL.Database("localhost:3306", "chinook"),
						  #"Navigation 1" = Source{[Schema = "chinook", Item = "invoiceline"]}[Data],
						    #"Expanded chinook.invoice" = Table.ExpandRecordColumn(#"Navigation 1", "chinook.invoice", {"CustomerId", "InvoiceDate"}, {"chinook.invoice.CustomerId", "chinook.invoice.InvoiceDate"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Expanded chinook.invoice",{{"chinook.invoice.CustomerId", "CustomerId"}, {"chinook.invoice.InvoiceDate", "InvoiceDate"}}),
						    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"chinook.track"}),
						    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"InvoiceDate", type date}})
						in
						    #"Changed Type"

			changedProperty = Name

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table DimTrack
			lineageTag: 4661206d-b2e7-4728-aa9d-6cc67fe479d2

			column TrackId
				dataType: int64
				formatString: 0
				lineageTag: 94321345-06c6-46e1-818d-b59107513ad3
				summarizeBy: none
				sourceColumn: TrackId

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column 'Track Name'
				dataType: string
				lineageTag: 003b54ca-5917-41fa-ae20-fc0870ff0fa5
				summarizeBy: none
				sourceColumn: Track Name

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column AlbumId
				dataType: int64
				formatString: 0
				lineageTag: 3a8ec4a4-71a3-4cf0-a46e-e6626d2d9b8f
				summarizeBy: none
				sourceColumn: AlbumId

				changedProperty = IsHidden

				annotation SummarizationSetBy = User

			column MediaTypeId
				dataType: int64
				formatString: 0
				lineageTag: 2b504218-24c5-496a-8c55-34733d5f555f
				summarizeBy: none
				sourceColumn: MediaTypeId

				changedProperty = IsHidden

				annotation SummarizationSetBy = User

			column GenreId
				dataType: int64
				formatString: 0
				lineageTag: f9317faf-092d-4d00-a27a-d46b6e75018d
				summarizeBy: none
				sourceColumn: GenreId

				changedProperty = IsHidden

				annotation SummarizationSetBy = User

			column Composer
				dataType: string
				lineageTag: 4228b49e-466b-4994-ae8d-4e85daa1629e
				summarizeBy: none
				sourceColumn: Composer

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column Milliseconds
				dataType: int64
				formatString: 0
				lineageTag: 27e54846-76cb-499e-9a86-1ed2134463f1
				summarizeBy: none
				sourceColumn: Milliseconds

				changedProperty = IsHidden

				annotation SummarizationSetBy = User

			column Bytes
				dataType: int64
				formatString: 0
				lineageTag: 76f70193-ef0c-4dfb-82a9-f27739e457d2
				summarizeBy: none
				sourceColumn: Bytes

				changedProperty = IsHidden

				annotation SummarizationSetBy = User

			column ListPrice
				dataType: double
				lineageTag: 2111f13d-3c45-4ad0-9ca8-b741d891f8e8
				summarizeBy: none
				sourceColumn: ListPrice

				changedProperty = IsHidden

				annotation SummarizationSetBy = User

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column 'Album Title'
				dataType: string
				lineageTag: c0ebd5c8-0658-4475-b93d-0147732c6b8f
				summarizeBy: none
				sourceColumn: Album Title

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column Genre
				dataType: string
				lineageTag: ebf3e6bc-cf2c-47eb-96f4-865e6bcca319
				summarizeBy: none
				sourceColumn: Genre

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column MediaType
				dataType: string
				lineageTag: ee5336d2-61c7-4a08-b386-447ffaf98bf7
				summarizeBy: none
				sourceColumn: MediaType

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column ArtistId
				dataType: int64
				formatString: 0
				lineageTag: e868b3b7-47e3-4b9b-b8ca-db89fc559ad9
				summarizeBy: none
				sourceColumn: ArtistId

				changedProperty = IsHidden

				annotation SummarizationSetBy = User

			column 'Artist Name'
				dataType: string
				lineageTag: 50df0de5-38c4-469b-ac2b-963b7b119dee
				summarizeBy: none
				sourceColumn: Artist Name

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			partition DimTrack = m
				mode: import
				source =
						let
						  Source = MySQL.Database("localhost:3306", "chinook"),
						  #"Navigation 1" = Source{[Schema = "chinook", Item = "track"]}[Data],
						    #"Expanded chinook.album" = Table.ExpandRecordColumn(#"Navigation 1", "chinook.album", {"Title", "ArtistId", "chinook.artist"}, {"chinook.album.Title", "chinook.album.ArtistId", "chinook.album.chinook.artist"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Expanded chinook.album",{{"chinook.album.Title", "Title"}}),
						    #"Expanded chinook.genre" = Table.ExpandRecordColumn(#"Renamed Columns", "chinook.genre", {"Name"}, {"chinook.genre.Name"}),
						    #"Removed Columns" = Table.RemoveColumns(#"Expanded chinook.genre",{"chinook.invoiceline"}),
						    #"Expanded chinook.mediatype" = Table.ExpandRecordColumn(#"Removed Columns", "chinook.mediatype", {"Name"}, {"chinook.mediatype.Name"}),
						    #"Removed Columns1" = Table.RemoveColumns(#"Expanded chinook.mediatype",{"chinook.playlisttrack"}),
						    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"chinook.genre.Name", "Genre"}, {"chinook.mediatype.Name", "MediaType"}, {"Title", "Album Title"}}),
						    #"Expanded chinook.album.chinook.artist" = Table.ExpandRecordColumn(#"Renamed Columns1", "chinook.album.chinook.artist", {"Name"}, {"chinook.album.chinook.artist.Name"}),
						    #"Renamed Columns2" = Table.RenameColumns(#"Expanded chinook.album.chinook.artist",{{"chinook.album.chinook.artist.Name", "Artist Name"}, {"chinook.album.ArtistId", "ArtistId"}, {"UnitPrice", "ListPrice"}, {"Name", "Track Name"}})
						in
						    #"Renamed Columns2"

			changedProperty = Name

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table DimCustomer
			lineageTag: 54a688ca-5da2-4fe0-9965-09914965888f

			column CustomerId
				dataType: int64
				formatString: 0
				lineageTag: a3a01fb6-3ac7-4828-a21b-1cd41a79f6ea
				summarizeBy: none
				sourceColumn: CustomerId

				annotation SummarizationSetBy = Automatic

			column FirstName
				dataType: string
				lineageTag: b8f79868-e8ba-4128-9e05-e810588e09f2
				summarizeBy: none
				sourceColumn: FirstName

				annotation SummarizationSetBy = Automatic

			column LastName
				dataType: string
				lineageTag: c2782f3b-dee2-4167-b2f6-51798b465125
				summarizeBy: none
				sourceColumn: LastName

				annotation SummarizationSetBy = Automatic

			column Company
				dataType: string
				lineageTag: f0d4e76f-7a07-48db-a3a3-4a4cba6b2410
				summarizeBy: none
				sourceColumn: Company

				annotation SummarizationSetBy = Automatic

			column Address
				dataType: string
				lineageTag: 2ccd4d20-aaf7-42b8-aeaf-96d474c26f2a
				summarizeBy: none
				sourceColumn: Address

				annotation SummarizationSetBy = Automatic

			column City
				dataType: string
				lineageTag: 13317c2d-eeaa-4741-9467-c8b8c694d40a
				summarizeBy: none
				sourceColumn: City

				annotation SummarizationSetBy = Automatic

			column State
				dataType: string
				lineageTag: 9a9d2c33-792b-4b87-9f1e-c536afd1b45e
				summarizeBy: none
				sourceColumn: State

				annotation SummarizationSetBy = Automatic

			column Country
				dataType: string
				lineageTag: 1606f60e-d313-4646-a3e6-c764c690a798
				summarizeBy: none
				sourceColumn: Country

				annotation SummarizationSetBy = Automatic

			column PostalCode
				dataType: string
				lineageTag: f01e4bc8-144c-41eb-8741-863b70179ce0
				summarizeBy: none
				sourceColumn: PostalCode

				annotation SummarizationSetBy = Automatic

			column Phone
				dataType: string
				lineageTag: e1152e84-7e10-4bf8-b8b1-e7a23623b3b0
				summarizeBy: none
				sourceColumn: Phone

				annotation SummarizationSetBy = Automatic

			column Fax
				dataType: string
				lineageTag: 181b6d72-0ded-4c58-abe2-c59ed02d1ef0
				summarizeBy: none
				sourceColumn: Fax

				annotation SummarizationSetBy = Automatic

			column Email
				dataType: string
				lineageTag: 4d4197d2-6a39-4051-890f-2cfe33029c2c
				summarizeBy: none
				sourceColumn: Email

				annotation SummarizationSetBy = Automatic

			column SupportRepId
				dataType: int64
				formatString: 0
				lineageTag: 1c5f2eb1-c94a-463a-be0b-47c30137294b
				summarizeBy: none
				sourceColumn: SupportRepId

				annotation SummarizationSetBy = Automatic

			column Employee_LastName
				dataType: string
				lineageTag: ce436587-a6ce-4f4c-89ac-a83104dca878
				summarizeBy: none
				sourceColumn: Employee_LastName

				annotation SummarizationSetBy = Automatic

			column Employee_FirstName
				dataType: string
				lineageTag: bc5a0fe6-a0f0-4caf-89fd-17f50880e373
				summarizeBy: none
				sourceColumn: Employee_FirstName

				annotation SummarizationSetBy = Automatic

			column Employee_Email
				dataType: string
				lineageTag: caea2940-7e0f-4649-bae2-4552f4a59bcc
				summarizeBy: none
				sourceColumn: Employee_Email

				annotation SummarizationSetBy = Automatic

			partition DimCustomer = m
				mode: import
				source =
						let
						  Source = MySQL.Database("localhost:3306", "chinook"),
						  #"Navigation 1" = Source{[Schema = "chinook", Item = "customer"]}[Data],
						    #"Expanded chinook.employee" = Table.ExpandRecordColumn(#"Navigation 1", "chinook.employee", {"LastName", "FirstName", "Email"}, {"chinook.employee.LastName", "chinook.employee.FirstName", "chinook.employee.Email"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Expanded chinook.employee",{{"chinook.employee.LastName", "Employee_LastName"}, {"chinook.employee.FirstName", "Employee_FirstName"}, {"chinook.employee.Email", "Employee_Email"}})
						in
						    #"Renamed Columns"

			changedProperty = Name

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table DimPlaylist
			lineageTag: 64ebbe5d-6e56-410c-aa7e-f34265fa4f95

			column PlaylistId
				dataType: int64
				formatString: 0
				lineageTag: cfdc20f5-8817-4ba2-a1c1-91dfcf680530
				summarizeBy: none
				sourceColumn: PlaylistId

				annotation SummarizationSetBy = Automatic

			column 'Playlist Name'
				dataType: string
				lineageTag: 00bba12d-b6a5-40fb-ae59-21aac253bc23
				summarizeBy: none
				sourceColumn: Playlist Name

				annotation SummarizationSetBy = Automatic

			column Id_Name = DimPlaylist[PlaylistId] & " - " & DimPlaylist[Playlist Name]
				lineageTag: 95501a3e-0ca4-44d7-9471-a465b7b8f521
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			partition DimPlaylist = m
				mode: import
				source =
						let
						  Source = MySQL.Database("localhost:3306", "chinook"),
						  #"Navigation 1" = Source{[Schema = "chinook", Item = "playlist"]}[Data],
						    #"Removed Columns" = Table.RemoveColumns(#"Navigation 1",{"chinook.playlisttrack"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Name", "Playlist Name"}})
						in
						  #"Renamed Columns"

			changedProperty = Name

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table DimDate
			lineageTag: 095f9ca5-17bc-4809-b777-abe6f2e611b9
			dataCategory: Time

			column Date
				isKey
				formatString: General Date
				lineageTag: 406a42a4-6cd5-489f-81bb-59450da1e6a8
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				annotation SummarizationSetBy = Automatic

			column Year
				formatString: 0
				lineageTag: 5e1c8686-cd6b-41a5-84ce-81aa0020668f
				summarizeBy: none
				isNameInferred
				sourceColumn: [Year]

				annotation SummarizationSetBy = Automatic

			column Month
				lineageTag: f44e2bab-b379-42b6-bcc1-6568a3bf8005
				summarizeBy: none
				isNameInferred
				sourceColumn: [Month]
				sortByColumn: MonthNo

				annotation SummarizationSetBy = Automatic

			column MonthNo
				formatString: 0
				lineageTag: 074a0aff-6d74-427c-ac3d-11accdd54b01
				summarizeBy: none
				isNameInferred
				sourceColumn: [MonthNo]

				annotation SummarizationSetBy = Automatic

			column Quarter
				lineageTag: 01db1010-ed11-44ca-882c-2a22419f35cf
				summarizeBy: none
				isNameInferred
				sourceColumn: [Quarter]

				annotation SummarizationSetBy = Automatic

			column YearMonth
				lineageTag: d6694d9c-82e4-4eff-a86d-75fea1cf2530
				summarizeBy: none
				isNameInferred
				sourceColumn: [YearMonth]

				annotation SummarizationSetBy = Automatic

			partition DimDate = calculated
				mode: import
				source =
						
						ADDCOLUMNS(
						    CALENDAR(
						        DATE(YEAR(MIN(FactSales[InvoiceDate])), 1, 1),
						        DATE(YEAR(MAX(FactSales[InvoiceDate])), 12, 31)
						    ),
						    "Year", YEAR([Date]),
						    "Month", FORMAT([Date], "MMM"),
						    "MonthNo", MONTH([Date]),
						    "Quarter", "Q" & QUARTER([Date]),
						    "YearMonth", FORMAT([Date], "YYYY-MM")
						)

			annotation PBI_Id = 0aefd0b7d0b64bf8976505d93e6b0bb3

		table MeauresTable
			lineageTag: a75acf23-77aa-473b-8e27-22f0707e21aa

			measure Sales =
					
					SUMX(
					    FactSales,
					    FactSales[Quantity]*FactSales[UnitPrice]
					)
				lineageTag: 4555fee4-7f88-42b9-9d39-d413a84c93e1

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Tracks Sold' = SUM(FactSales[Quantity])
				formatString: 0
				lineageTag: 7205ca63-5a30-43d4-9202-1fdbd8899e56

			measure 'Sales PY' =
					
					CALCULATE(
					    [Sales],
					    SAMEPERIODLASTYEAR(DimDate[Date])
					)
				lineageTag: 74caaa38-0250-4688-a84a-71a2465660f5

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Customers Sold' = ```
					
					// DISTINCTCOUNT(DimCustomer[CustomerId])
					VAR _T = 
					    ADDCOLUMNS(
					        VALUES(DimCustomer[CustomerId]),
					        "_Quantity",[Tracks Sold]
					    )
					RETURN
					COUNTX(_T,DimCustomer[CustomerId])
					```
				formatString: 0
				lineageTag: 1abf4331-7c7b-4b01-8b46-adc155c89576

			measure 'Countries Sold' = DISTINCTCOUNT(DimCustomer[Country])
				formatString: 0
				lineageTag: f55d0051-534c-4aca-b891-3ab8cd444a1e

			measure 'Sales Per Invoice' =
					
					DIVIDE([Sales],[Invoice Count])
				lineageTag: c4df8c51-f82e-4c4e-8e1d-f9b3bfa1454d

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Invoice Count' = DISTINCTCOUNT(FactSales[InvoiceId])
				formatString: 0
				lineageTag: 0906f517-ed37-4143-864d-cfc79ec5eaa3

			measure 'Avg Price CY' = DIVIDE([Sales],[Tracks Sold])
				lineageTag: 3c617ffa-6344-4f7e-bd40-49989259792e

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Tracks Sold PY' = CALCULATE([Tracks Sold],SAMEPERIODLASTYEAR(DimDate[Date]))
				formatString: 0
				lineageTag: aac48528-0be1-4dc1-821e-2d18cbb87453

			measure 'Avg Price PY' = DIVIDE([Sales PY],[Tracks Sold PY])
				lineageTag: cd4993dc-a361-4ad0-a8b1-fb0902c0d7b0

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			partition MeauresTable = m
				mode: import
				source =
						let
						  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
						    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
						in
						  #"Removed Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table TopCategory
			lineageTag: 8d0a6ffd-1f51-48e3-8808-a75e9b89e3c5

			measure TopBottomSales = ```
					
					VAR _sel = SELECTEDVALUE(TopCategory[TopCategory Order])
					VAR _rank_desc = 
					        SWITCH(
					            _sel,
					            0,RANKX(ALL(DimTrack[Album Title]),[Selected Metric],,DESC,Dense),
					            1,RANKX(ALL(DimTrack[Artist Name]),[Selected Metric],,DESC,Dense),
					            2,RANKX(ALL(DimTrack[Track Name]),[Selected Metric],,DESC,Dense),
					            BLANK())
					RETURN
					IF(_rank_desc<=5,[Selected Metric])
					```
				lineageTag: 6414610d-edc9-429c-9475-bcb0cde26627

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column TopCategory
				lineageTag: 5cc42c4b-72a4-419d-a22d-ff55875511bd
				summarizeBy: none
				sourceColumn: [Value1]
				sortByColumn: 'TopCategory Order'

				relatedColumnDetails
					groupByColumn: 'TopCategory Fields'

				annotation SummarizationSetBy = Automatic

			column 'TopCategory Fields'
				isHidden
				lineageTag: a34def10-e651-42a3-881c-f7ad7f9ace24
				summarizeBy: none
				sourceColumn: [Value2]
				sortByColumn: 'TopCategory Order'

				extendedProperty ParameterMetadata = {"version":3,"kind":2}

				annotation SummarizationSetBy = Automatic

			column 'TopCategory Order'
				isHidden
				formatString: 0
				lineageTag: 8789a833-0809-4aa6-a10e-65a6366a38da
				summarizeBy: sum
				sourceColumn: [Value3]

				annotation SummarizationSetBy = Automatic

			partition TopCategory = calculated
				mode: import
				source =
						{
						    ("Album Title", NAMEOF('DimTrack'[Album Title]), 0),
						    ("Artist Name", NAMEOF('DimTrack'[Artist Name]), 1),
						    ("Track Name", NAMEOF('DimTrack'[Track Name]), 2)
						}

			annotation PBI_Id = 9df388dbacbf449c8562e8c679bca64c

		table TopBottomAnalysis
			lineageTag: ac2d20ac-918d-49d2-adcd-a2903808dc13

			column Ranking
				dataType: string
				lineageTag: 0f04fc25-d79a-40a9-b76e-44961d657bae
				summarizeBy: none
				sourceColumn: Ranking

				annotation SummarizationSetBy = Automatic

			partition TopBottomAnalysis = m
				mode: import
				source =
						let
						  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCskvUIrViVZyyi8pyc9Vio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Ranking = _t])
						in
						  Source

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table MeasureParameter
			lineageTag: dfc807a5-022a-4428-afd7-fe4e6a4fc500

			measure 'Selected Metric' =
					
					SWITCH
					    (
					        SELECTEDVALUE(MeasureParameter[MeasureParameter Order]),
					        0,[Tracks Sold],
					        1,[Sales],
					        2,[Invoice Count]
					)
				lineageTag: 78e3990c-5ace-40e4-998a-ed7cc0be808f

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column MeasureParameter
				lineageTag: ebba630f-f6e1-4adf-b59e-8a5a712fba39
				summarizeBy: none
				sourceColumn: [Value1]
				sortByColumn: 'MeasureParameter Order'

				relatedColumnDetails
					groupByColumn: 'MeasureParameter Fields'

				annotation SummarizationSetBy = Automatic

			column 'MeasureParameter Fields'
				isHidden
				lineageTag: 9adbf55d-1b4c-4701-969e-7e0b09e9af01
				summarizeBy: none
				sourceColumn: [Value2]
				sortByColumn: 'MeasureParameter Order'

				extendedProperty ParameterMetadata = {"version":3,"kind":2}

				annotation SummarizationSetBy = Automatic

			column 'MeasureParameter Order'
				isHidden
				formatString: 0
				lineageTag: 83110861-9d78-448d-ba20-52065b404e81
				summarizeBy: sum
				sourceColumn: [Value3]

				annotation SummarizationSetBy = Automatic

			partition MeasureParameter = calculated
				mode: import
				source =
						{
						    ("Tracks Sold", NAMEOF('MeauresTable'[Tracks Sold]), 0),
						    ("Sales",NAMEOF('MeauresTable'[Sales]),1),
						    ("Invoice Count",NAMEOF('MeauresTable'[Invoice Count]),2)
						}

			annotation PBI_Id = 6982b92d536d47d4bd579a0feea49d6a

		table 'Calculation group'
			lineageTag: 06c9d924-4b80-488a-8b17-559a0decc2ca

			calculationGroup

				calculationItem 'Current Value' = SELECTEDMEASURE()

				calculationItem PY =
						
						CALCULATE(
						    SELECTEDMEASURE(),
						    SAMEPERIODLASTYEAR(DimDate[Date])
						)

			column 'Calculation group column'
				dataType: string
				lineageTag: 9fbdbbcd-d0dd-46f4-98c4-199bbf938509
				summarizeBy: none
				sourceColumn: Name
				sortByColumn: Ordinal

				annotation SummarizationSetBy = Automatic

			column Ordinal
				dataType: int64
				formatString: 0
				lineageTag: 0072f600-b86f-4e2b-be2c-95df869b4adf
				summarizeBy: sum
				sourceColumn: Ordinal

				annotation SummarizationSetBy = Automatic

		relationship 3aa1742b-2ec4-fae8-a6cd-1b8139b31b80
			fromColumn: FactSales.CustomerId
			toColumn: DimCustomer.CustomerId

		relationship e474cd7b-e382-4b57-7625-0df1c7230c2e
			fromColumn: FactSales.TrackId
			toColumn: DimTrack.TrackId

		relationship e4f6ea54-43da-89cf-464d-5f8813883d22
			crossFilteringBehavior: bothDirections
			fromColumn: BridgePlaylisttrack.TrackId
			toColumn: DimTrack.TrackId

		relationship AutoDetected_3132cb1f-62d6-425f-bfb1-58d3ff130027
			fromColumn: BridgePlaylisttrack.PlaylistId
			toColumn: DimPlaylist.PlaylistId

		relationship ac5cbe47-97ba-4b9c-1ea4-f13e71daac09
			fromColumn: FactSales.InvoiceDate
			toColumn: DimDate.Date

		cultureInfo en-US

		expression 'chinook album' =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "album"]}[Data]
				in
				  #"Navigation 1"
			lineageTag: c90f297d-cf4b-49a7-9b00-48d1af7830a2
			queryGroup: SourceFiles

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'chinook artist' =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "artist"]}[Data]
				in
				  #"Navigation 1"
			lineageTag: 4b80063d-1c0a-44da-b60f-7e4ed75b7a15
			queryGroup: SourceFiles

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'chinook customer' =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "customer"]}[Data]
				in
				  #"Navigation 1"
			lineageTag: 27cbfe5a-91fa-4471-b8d2-86037bd00d1d
			queryGroup: SourceFiles

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'chinook employee' =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "employee"]}[Data]
				in
				  #"Navigation 1"
			lineageTag: 1df5437c-47e7-4c9e-ac71-edc835d9ac7f
			queryGroup: SourceFiles

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'chinook genre' =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "genre"]}[Data]
				in
				  #"Navigation 1"
			lineageTag: 053b9cfe-6c16-415a-969d-9c4ec3741f6e
			queryGroup: SourceFiles

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'chinook invoice' =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "invoice"]}[Data]
				in
				  #"Navigation 1"
			lineageTag: f929e3a7-68ac-4f05-984a-ee92ad981590
			queryGroup: SourceFiles

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'chinook invoiceline' =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "invoiceline"]}[Data]
				in
				  #"Navigation 1"
			lineageTag: 122a1997-db45-4069-958d-6938076c58a4
			queryGroup: SourceFiles

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'chinook mediatype' =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "mediatype"]}[Data]
				in
				  #"Navigation 1"
			lineageTag: ed177e35-040f-404b-a841-c29ac3ae9e8a
			queryGroup: SourceFiles

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'chinook track' =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "track"]}[Data]
				in
				  #"Navigation 1"
			lineageTag: dcd2c5dc-6371-4acb-8fef-3dccb0f01419
			queryGroup: SourceFiles

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'chinook playlisttrack' =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "playlisttrack"]}[Data]
				in
				    #"Navigation 1"
			lineageTag: 7107eb59-a7ad-4052-b597-13fe2cbfb160
			queryGroup: SourceFiles

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'chinook playlist' =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "playlist"]}[Data]
				in
				  #"Navigation 1"
			lineageTag: 4a2dea22-8e36-4ca3-bbff-6f3eba4bffc2
			queryGroup: SourceFiles

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		queryGroup SourceFiles

			annotation PBI_QueryGroupOrder = 0

		annotation __PBI_TimeIntelligenceEnabled = 0

		annotation PBI_QueryOrder = ["chinook album","chinook artist","chinook customer","chinook employee","chinook genre","chinook invoice","chinook invoiceline","chinook mediatype","chinook playlist","BridgePlaylisttrack","chinook track","FactSales","DimTrack","DimCustomer","DimPlaylist","chinook playlisttrack","MeauresTable","TopBottomAnalysis"]

		annotation PBI_ProTooling = ["TMDLView_Desktop","CalcGroup","DaxQueryView_Desktop"]

