table FactSales
	lineageTag: a373dbed-3ba1-4880-bc2b-fa2263f031fe

	column InvoiceLineId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e7469481-4082-4f95-abf1-09035e861d7a
		summarizeBy: none
		sourceColumn: InvoiceLineId

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column InvoiceId
		dataType: int64
		formatString: 0
		lineageTag: 1b86e457-ff14-4f8b-a478-065ec97b900b
		summarizeBy: none
		sourceColumn: InvoiceId

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column TrackId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 765cb33b-5d54-4364-865f-a75a34ee88ad
		summarizeBy: none
		sourceColumn: TrackId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 59bc9ec8-1bd8-4e77-bb57-803cf74c01fc
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: d474b074-e82d-4e07-8119-42fd183055c4
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column CustomerId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 21f6a973-a7a2-49c6-82c0-4ca9ec4bcb90
		summarizeBy: none
		sourceColumn: CustomerId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InvoiceDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 1772547f-f89b-4754-a847-583a5c4341e0
		summarizeBy: none
		sourceColumn: InvoiceDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FactSales = m
		mode: import
		source =
				let
				  Source = MySQL.Database("localhost:3306", "chinook"),
				  #"Navigation 1" = Source{[Schema = "chinook", Item = "invoiceline"]}[Data],
				    #"Expanded chinook.invoice" = Table.ExpandRecordColumn(#"Navigation 1", "chinook.invoice", {"CustomerId", "InvoiceDate"}, {"chinook.invoice.CustomerId", "chinook.invoice.InvoiceDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded chinook.invoice",{{"chinook.invoice.CustomerId", "CustomerId"}, {"chinook.invoice.InvoiceDate", "InvoiceDate"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"chinook.track"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"InvoiceDate", type date}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

